### ISSUE TITLE
No output after [net] add project

### ISSUE THREAD

**Issue by Pantsi** [wwww-wwww/grav1#1]
Hi, trying to get this working under win10.

When i posting this json to server i getting the response true.

`{
    "input":  [
                  "test.mkv, test1.mkv"
              ],
    "encoder":  "aom",
    "on_complete":  "merge",
    "encoder_params":  "--lag-in-frames=25 -b 10 --cpu-used=3"
}`

Only output i get from server is but after that no more.
[net] add project ['test.mkv, test1.mkv']

Also only getting [] when i visiting /api/get_projects

Running this on win10 with python 3.7 and flask, flask-cors, wsgiserver installed by pip.
The testfiles is in the same folder as grav1, also in that folder is ffmpeg, aomenc, vpxenc. 
Are i missing something in the setup?

**Comment by wwww-wwww** [comment]
It looks like you're attempting to add a single file literally named "test.mkv, test1.mkv".
There's currently no message for having not found any files. I'll make a patch for that.

Also don't forget about also having the dav1d binary for now. I'll make it optional later aswell.

**Comment by Pantsi** [comment]
Thanks for the help so far! Getting new errors now
`{
    "input":  [
                  "00000.mkv",
                  "00001.mkv"
              ],
    "encoder":  "aom",
    "on_complete":  "merge",
    "encoder_params":  "--lag-in-frames=25 -b 10 --cpu-used=3"
}

[net] add project ['00000.mkv', '00001.mkv']
[2020-07-07 10:49:40,378] ERROR in app: Exception on /api/add_project [POST]
Traceback (most recent call last):
  File "C:\Users\...\Python37\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\...\Python37\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\...\Python37\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\...\Python37\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\...\Python37\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\...\Python37\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\...\Python37\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File ".\server.py", line 169, in add_project
    self.projects.add(Project(
NameError: name 'self' is not defined`

**Comment by wwww-wwww** [comment]
Ah yes, silly mistake when refactoring.
Should be fixed in this commit.
https://github.com/wwww-wwww/grav1/commit/54d5f30868ef7705e754977e75ac593d0e56f7a3#diff-d355af669766ee3562643e8e5034f715R169

**Comment by Pantsi** [comment]
Works greate now, big thanks :)
